sudo: required
services:
  - docker

before_install:
  - docker build -t octavianmitu/react-test -f ./client/Dockerfile --target dev ./client

script:
  - docker run -e CI=true octavianmitu/react-test npm run test -- --coverage

after_success:
  - docker build -t octavianmitu/multi-nginx ./nginx
  - docker build -t octavianmitu/multi-server ./server
  - docker build -t octavianmitu/multi-worker ./worker
  - docker build -t octavianmitu/multi-client ./client

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push octavianmitu/multi-nginx
  - docker push octavianmitu/multi-server
  - docker push octavianmitu/multi-worker
  - docker push octavianmitu/multi-client


deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-656983766737
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_KEY
  on:
    branch: main